[package]
name = "first_cargo_proj"
version = "0.1.0"
authors = ["Shinya Yaginuma <shinya.yaginuma.0507@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
